apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-app-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>DevOps Demo</title>

      <style>
        body {
          margin: 0;
          font-family: Arial, sans-serif;
          background: linear-gradient(135deg, #ffffff, #f97316);
          color: #1e293b;
          text-align: center;
        }

        header {
          background-color: #ea580c;
          color: white;
          padding: 20px;
          font-size: 24px;
        }

        .container {
          margin-top: 60px;
        }

        h1 {
          font-size: 42px;
          color: #ea580c;
        }

        .subtitle {
          font-size: 20px;
          margin-top: 10px;
        }

        .card {
          background: white;
          margin: 40px auto;
          padding: 25px;
          width: 320px;
          border-radius: 12px;
          box-shadow: 0 6px 15px rgba(0,0,0,0.2);
        }

        .footer {
          margin-top: 50px;
          font-size: 16px;
          color: #444;
        }
      </style>
    </head>

    <body>

      <header>
         DevOps Project - ArgoCD + Kubernetes
      </header>

      <div class="container">
        <h1>Bienvenue </h1>

        <p class="subtitle">
          This is a Spring Boot demo application – version <strong>v1.0</strong>
        </p>

        <div class="card">
          <h3>CI/CD Pipeline</h3>
          <p>Built with Jenkins</p>
          <p>Deployed with ArgoCD</p>
        </div>

        <p class="footer">
          End-to-end CI/CD pipeline with Kubernetes, Jenkins and ArgoCD
        </p>
      </div>

   
      <footer>
         2026 - DevOps Demo by Lauraine
      </footer>

    </body>
    </html>
